name: Build

on:
  push:
    branches:
      - main
      - ci-wip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Configure keystore
        run: |
          ./prepare-keystore.sh

      - name: Pull builder image
        run: |
          make docker-pull

      - name: Build
        run: |
          make docker-build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apks
          path: app/build/outputs/apk/**/*.apk
